# Uncomment the next line to define a global platform for your project

platform :ios, '7.0'

target 'example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for example
pod 'AFNetworking'
pod 'SDCycleScrollView','~> 1.66'
end
